export const SET_IS_INITIAL_ROUTE = 'VUE_FETCH_ROUTE__DEFAULT__SET_IS_INITIAL_ROUTE';
export const SET_ROUTE_DATA = 'VUE_FETCH_ROUTE__DEFAULT__SET_ROUTE_DATA';
export const SET_PARTIALS_DATA = 'VUE_FETCH_ROUTE__DEFAULT__SET_PARTIALS_DATA';
export const SET_LOADING_STATE = 'VUE_FETCH_ROUTE__DEFAULT__SET_LOADING_STATE';
export const FLUSH_CACHE = 'VUE_FETCH_ROUTE__DEFAULT__FLUSH_CACHE';
